ICourses/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICourses.ViewModels;
using ICourses.Entities;
using Microsoft.AspNetCore.Authorization;
using ICourses.Services.Interfaces;

namespace ICourses.Controllers
{
    public class SubjectsController : Controller
    {       
        ISubjectService _subjectService;

        public SubjectsController(ISubjectService subjectService)
        {
            _subjectService = subjectService;
        }
       
        public async Task<IActionResult> Index()
        {
            return View(await _subjectService.GetAllSubject());
        }
       
        public async Task<IActionResult> Details(Guid id)
        {
            var subject = await _subjectService.GetSubject(id);

            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }



        [Authorize(Roles = "admin,moderator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,moderator")]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Subject subject)
        {
            if (ModelState.IsValid)
            { 
                await _subjectService.AddSubject(subject);
                
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        [Authorize(Roles = "admin,moderator")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var subject = await _subjectService.GetSubject(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,moderator")]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Description")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                await _subjectService.UpdateSubject(subject);     
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        [Authorize(Roles = "admin,moderator")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var subject = await _subjectService.GetSubject(id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,moderator")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var subject = await _subjectService.GetSubject(id);
            await _subjectService.DeleteSubject(subject);
            return RedirectToAction(nameof(Index));
        }

        //private bool SubjectExists(Guid id)
        //{
        //    return _context.Subjects.Any(e => e.Id == id);
        //}
    }
}

ICourses/Views/Subjects/Create.cshtml
@model ICourses.Entities.Subject
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Добавить предмет";
}

<section class="eight">
    <div class="container">
        <div class="contacts">
            <div class="why-text text-white">
                <h3>@localizer["text"] </h3>
            </div>
            <hr />
            <div class="contacts-content">

                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div style="width:600px" class="form-group">
                        <label asp-for="Name" class="control-label text-white">@localizer["Name"]</label>
                        <input  class="form-control input-text" asp-for="Name" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Description" class="control-label text-white">@localizer["Description"]</label>
                        <textarea asp-for="Description" class="textarea form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@localizer["Create"]" class="button-active" />
                    </div>

                </form>

            </div>
        </div>

        @*<div>
            <a asp-action="Index">Back to List</a>
        </div>*@
    </div>
</section>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

ICourses/Views/Subjects/Details.cshtml
@model ICourses.Entities.Subject
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Index";
}



    <div class="container p-3 text-center">
        <h1 class="text-success">@Model.Name</h1>
        <h6 class="m-3 text-muted">@Model.Description</h6>
    </div>


<div class="row mb-2">
    @if (Model.Courses != null)
    {
        @foreach (var item in Model.Courses)
        {
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <h5 class="mb-0 text-white ">@item.Name</h5>
                        <div class="mb-1 text-muted">@item.Modified</div>

                        <div class="mb-1 text-muted">@localizer["Lang"]:  @item.Language</div>

                        <p class="card-text mb-auto text-white">@item.Description</p>
                        <a class="button-active" asp-controller="Courses" asp-action="Details" asp-route-id="@item.Id" role="button">
                            @localizer["Start"]
                        </a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img style='width:200px; height:200px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(@item.Image))" />
                    </div>
                    @if (User.IsInRole("admin") || User.IsInRole("teacher"))
                    {
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary" role="button" asp-controller="Courses" asp-action="Edit" asp-route-id="@item.Id">
                                    @localizer["Editbtn"]
                                </a>
                                <form asp-controller="Courses" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        @localizer["Deletebtn"]
                                    </button>
                                </form>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    }
</div>


@if (User.IsInRole("admin") || User.IsInRole("teacher"))
{
    <p>
        <a class="button-active" asp-controller="Courses" asp-action="Create" asp-route-id="@Model.Id">@localizer["AddNewCourse"]</a>
    </p>
}

ICourses/Views/Subjects/Edit.cshtml
@model ICourses.Entities.Subject
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Edit";
}

<section class="eight">
    <div class="container">
        <div class="contacts">
            <div class="why-text text-white">

                <h3>@localizer["text"] @Model.Name</h3>

            </div>
            <hr />
            <div class="contacts-content">

                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">

                        <label asp-for="Name" class="control-label">@localizer["Name"]</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">

                        <label asp-for="Description" class="control-label">@localizer["Description"]</label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="@localizer["Save"]" class="btn btn-primary" />
                    </div>
                </form>

            </div>
        </div>
        @*<div>
            <a asp-action="Index">Back to List</a>
        </div>*@
    </div>
</section>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ICourses/Views/Subjects/Index.cshtml
@model IEnumerable<ICourses.Entities.Subject>
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Списки Предметов";
}


<section class="third">
    <div class="container">
        <div class="team">
            <div class="why-text text-white text-md-center">

                <h3 class="text-success">@localizer["list"]</h3>

            </div>
            <div class="team-content">
                <div class="team-cards">
                    @foreach (var m in Model)
                    {
        @if (User.IsInRole("admin"))
        {

        <div class="team-card revealator-slideleft revealator-delay1">
            <div class="team-card-text">

                <h2 class="text-lg-center">@Html.DisplayFor(modelItem => m.Name)</h2>
                <div class="team-card-links">
                    <p style="margin-left:10%">@Html.DisplayFor(modelItem => m.Description)</p>
                </div>
                <div  class="team-card-links">
                    <a style="margin-left:10%" class="button-active" asp-controller="Subjects" asp-action="Details" asp-route-id="@m.Id">
                        @localizer["DetailCourse"]
                    </a>

                </div>
                <form style="margin-left:10%; width:200px" asp-controller="Subjects" asp-action="Delete" asp-route-id="@m.Id" method="post">
                    <button style="width:135px; color:white; background-color:crimson" type="submit" class="button-active">
                        @localizer["Delete"]
                    </button>
                </form>
            </div>
        </div>}
    else
    {
        <div class="team-card revealator-slideleft revealator-delay1">
            <div class="team-card-text">

                <h2 class="text-lg-center">@Html.DisplayFor(modelItem => m.Name)</h2>
                <div class="team-card-links">
                    <p>@Html.DisplayFor(modelItem => m.Description)</p>
                </div>
                <div class="team-card-links">
                    <a style="margin-left:10%" class="button-active revealator-slideup revealator-delay3 nav" asp-controller="Subjects" asp-action="Details" asp-route-id="@m.Id">
                        @localizer["DetailCourse"]
                    </a>
                </div>

            </div>
        </div>}}

                </div>
            </div>
            <br>
            <br>

            @if (User.IsInRole("admin"))
            {
        <p>
            <a class="button-active revealator-slideup revealator-delay3 nav" asp-action="Create">
                @localizer["CreateNew"]
            </a>
        </p>}
        </div>
</section>