ICourses/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ICourses.Interfaces;
using System.IO;
using ICourses.Entities;
using ICourses.ViewModels;
using ICourses.Services.Interfaces;

namespace ICourses.Controllers
{
    [Authorize]
    public class ModulesController : Controller
    {       
         IModuleService _moduleService;
        ITextService _textService;
        IVideoService _videoService;
        //private readonly CourseDbContext _context;

        public ModulesController(IModuleService moduleService, IVideoService videoService, ITextService textService)
        {
            _videoService = videoService;
            _textService = textService;            
            _moduleService = moduleService;
        }

        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Module module = await _moduleService.GetModule(id);
            ViewBag.Texts = await _textService.GetAllTextMaterials(id);
            ViewBag.Videos = await _videoService.GetAllVideos(id);

            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }


       [Authorize(Roles = "admin,teacher")]
        public IActionResult Create(Guid? id)
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,teacher")]
        public async Task<IActionResult> Create(Guid id, CreateModuleViewModel module)
        {     
            if (ModelState.IsValid)
            {
                Module m = await _moduleService.AddModule(id, module);
                if(m != null)
                    return RedirectToAction("Details", "Courses", new { id = m.CourseId });
            }            
            return View();
            //return View(@module);
        }



        [Authorize(Roles = "admin,teacher")]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _moduleService.GetModule(id);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,teacher")]
        public async Task<IActionResult> Edit(Guid id, ChangeModuleViewModel module)
        {         
            if (ModelState.IsValid)
            {             
                Module new_module = await _moduleService.EditModule(id, module);

                if(new_module != null)
                    return RedirectToAction("Details", "Modules", new { id = id });                
            }            
            return View(@module);
        }

        [Authorize(Roles = "admin,teacher")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _moduleService.GetModule(id); 

            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,teacher")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var module = await _moduleService.GetModule(id);
            await _moduleService.DeleteModuleById(id);
            return RedirectToAction("Details", "Courses", new { id = module.CourseId });
        }
    }
}

ICourses/Controllers/TextMaterialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ICourses.ViewModels;
using ICourses.Entities;
using Microsoft.AspNetCore.Authorization;
using ICourses.Interfaces;
using ICourses.Services.Interfaces;

namespace ICourses.Controllers
{
    [Authorize]
    public class TextMaterialsController : Controller
    {
        ITextService _textService;

        public TextMaterialsController(ITextService textService)
        {
            _textService = textService;
        }

        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var textMaterial = await _textService.GetTextMaterial(id);

            if (textMaterial == null)
            {
                return NotFound();
            }

            return View(textMaterial);
        }

        [Authorize(Roles = "admin,teacher")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       [Authorize(Roles = "admin,teacher")]
        public async Task<IActionResult> Create(Guid id, TextViewModel text)
        {           
            if (ModelState.IsValid)
            {
                TextMaterial textMaterial = await _textService.AddTextMaterial(id, text);    
                if(textMaterial != null)      
                    return RedirectToAction("Details", "Modules", new { id = textMaterial.ModuleId });
            }
            return View(text);
        }

        [Authorize(Roles = "admin,moderator,teacher")]
        public async Task<IActionResult> Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var textMaterial = await _textService.GetTextMaterial(id);;
            if (textMaterial == null)
            {
                return NotFound();
            }
            //ViewData["ModuleId"] = new SelectList(_context.Modules, "Id", "Id", textMaterial.ModuleId);
            return View(textMaterial);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,moderator,teacher")]
        public async Task<IActionResult> Edit(Guid id, TextViewModel text)
        {
            if (ModelState.IsValid)
            {
                TextMaterial new_text = await _textService.EditTextMaterial(id, text);
                if (new_text != null)
                    return RedirectToAction("Details", "Modules", new { id = new_text.ModuleId });
            }
            return View(text);
        }

        [Authorize(Roles = "admin,moderator,teacher")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var textMaterial = await _textService.GetTextMaterial(id);
                
            if (textMaterial == null)
            {
                return NotFound();
            }

            return View(textMaterial);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
       [Authorize(Roles = "admin,moderator,teacher")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var textMaterial = await _textService.GetTextMaterial(id);
            await _textService.DeleteTextMaterialById(id);
            return RedirectToAction("Details", "Modules", new { id = textMaterial.ModuleId });
        }
    }
}

ICourses/Views/Modules/Create.cshtml
@model ICourses.Entities.Module
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Create";
}

<div class="title text-white">
    <h1 class="h2 mb-3 font-weight-normal">@localizer["CreateLable"]</h1>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="control-label text-white"></div>
            <div class="form-group">

                <label asp-for="Name" class="control-label  text-white">@localizer["Name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label text-white">@localizer["Description"]</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <label class="control-label text-white">@localizer["Image"]</label>
            <input name="Image" type="file" class="form-control" />

            <div class="form-group">
                <input type="submit" value="@localizer["Create"]" class="button-active" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ICourses/Views/Modules/Details.cshtml
@model ICourses.Entities.Module
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Details";
}

<div class="container m-1 my-3 p-3">
    <div class="container">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-4 col-lg-4 d-md-block sidebar collapse  no-gutters border rounded overflow-hidden shadow-sm position-relative">
                <div class="sidebar-sticky">
                    @if (@Model.TextMaterials != null)
                    {
                        <h5 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>@localizer["TextMat"]:</span>
                        </h5>

                        @foreach (var item in Model.TextMaterials)
                        {
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#@item.Id">
                                        <span data-feather="home"></span>
                                        @item.Name<span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            </ul>
                        }
                    }

                    @if (@Model.Videos != null)
                    {
                        <h5 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                            <span>@localizer["Videos"]:</span>

                        </h5>

                        @foreach (var item in Model.Videos)
                        {
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#@item.Id">
                                        <span data-feather="home"></span>
                                        @item.Name<span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            </ul>
                        }
                    }

                </div>
            </nav>

            <main role="main" class="col-md-7 ml-sm-auto col-lg-8 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <div class="featurette">

                        <div class="row featurette">
                            <div class="col-md-5">
                                <div class="text-center m-3">
                                    <h1 class="featurette-heading text-white">@Model.Name</h1>
                                </div>
                                <h6 class="text-muted">@Model.Modified</h6>

                                <p class="lead text-white">@localizer["ModuleDescription"]: @Model.Description</p>

                                @if (User.IsInRole("admin") || (User.IsInRole("teacher")))
                                {

                                    <p>
                                        <a class="btn btn-sm btn-outline-secondary" asp-action="Edit" asp-route-id="@Model.Id">@localizer["Editbtn"]</a>
                                        <form asp-action="Delete" asp-route-id="@Model.Id" method="post">
                                            <button type="submit" class="btn btn-sm btn-danger">
                                                @localizer["Deletebtn"]
                                            </button>
                                        </form>
                                    </p>
                                }
                            </div>
                            <div class="col-md-5">
                                <img style='width:250px; height:250px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(@Model.Image))" />
                            </div>
                        </div>
                        <hr />

                        <div class="col-md-8">
                            @if (@Model.TextMaterials != null)
                            {
                                @foreach (var item in Model.TextMaterials)
                                {
                                    <div class="blog-post">
                                        <h2 class="blog-post-title text-white"><a name="@item.Id">@item.Name</a></h2>
                                        <p class="blog-post-meta mb-1 text-muted">@item.Modified</p>
                                        <p class="text-white">@item.Context</p>

                                        @if (User.IsInRole("admin") ||  (User.IsInRole("teacher")))
                                        {

                                            <div class="d-flex justify-content-between align-items-center">
                                                <div class="btn-group">
                                                    <a class="btn btn-sm btn-outline-secondary" role="button" asp-controller="TextMaterials" asp-action="Edit" asp-route-id="@item.Id">
                                                        @localizer["Editbtn"]
                                                    </a>

                                                    <form asp-controller="TextMaterials" asp-action="Delete" asp-route-id="@item.Id" method="post">

                                                        <button type="submit" class="btn btn-sm btn-danger">
                                                            @localizer["Deletebtn"]
                                                        </button>
                                                    </form>
                                                </div>
                                            </div>
                                        }

                                    </div>
                                }
                            }
                        </div>


                        <div class="container m-3">
                            @if (User.IsInRole("admin") || (User.IsInRole("teacher")))
                            {
                                <p><a class="button-active revealator-slideup revealator-delay3" asp-area="" asp-controller="TextMaterials" asp-action="Create" asp-route-id="@Model.Id">
                                      @localizer["NewText"] </a></p>
                            }
                        </div>
                        <hr />

                        <div class="col-md-8">
                            @if (@Model.Videos != null)
                            {
                                @foreach (var v in ViewBag.Videos)
                                {
                            <div class="blog-post">
                                <h2 class="blog-post-title text-white"><a name="@v.Id">@v.Name</a></h2>

                                @* <div height="240" width="320" controls>
            <video width="320" height="240" controls>
                <source src=@v.Url type="video/mp4" />
            </video>
        </div>*@

                                @*<video width="640" height="480" controls>
            <source src=@v.Url type='video/ogg'>
            <source src=@v.Url type='video/mp4'>
            <source src=@v.Url type='video/webm'>
            Your browser does not support the video tag.
        </video>*@

                                <iframe width="640" height="480" src=@v.Url title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


                                @if (User.IsInRole("admin") ||  (User.IsInRole("teacher")))
                                {

                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-secondary" role="button" asp-controller="Videos" asp-action="Edit" asp-route-id="@v.Id">
                                        @localizer["Editbtn"]
                                    </a>

                                    <form asp-controller="Videos" asp-action="Delete" asp-route-id="@v.Id" method="post">

                                        <button type="submit" class="btn btn-sm btn-danger">
                                            @localizer["Deletebtn"]
                                        </button>
                                    </form>
                                </div>
                            </div>}

                            </div>
                                }
                            }
                        </div>

                        <div class="container m-3">
                            @if (User.IsInRole("admin") || (User.IsInRole("teacher")))
                            {

                                <p>
                                    <a class="button-active revealator-slideup revealator-delay3" asp-controller="Videos" asp-action="Create" asp-route-id="@Model.Id">
                                        @localizer["NewVideo"]
                                    </a>
                                </p>
                            }
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</div>

ICourses/Views/Modules/Edit.cshtml
@model ICourses.Entities.Module
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Edit";
}

<div class="title text-white">
    <h1 class="h2 mb-3 font-weight-normal">@localizer["CreateLable"]: @Model.Name</h1>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label text-white">@localizer["Name"]</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label text-white">@localizer["Description"]</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>


            <label class="control-label text-white">@localizer["Image"]</label>
            <input name="Image" type="file" class="form-control" />

            <div class="form-group">
                <input type="submit" value="@localizer["Save"]" class="button-active" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}